name: Validar CSV CIE10

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cache-version: [1]
        r-version: ['4.1.1']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Instalar R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with: 
        use-public-rspm: true
        r-version: ${{ matrix.r-version }}
    - name: Instalar paquete necesarios
      uses: r-lib/actions/setup-renv@v2
    - name: Correr validaciones
      run: |
        Rscript -e 'source("tests/testthat.R")'
      shell: bash {0}
